// ─── Onyx Void — Library Entry Point ───────────────────────────────
// Required for Android builds: the Makepad `app_main!()` macro
// generates JNI entry points when compiled as a cdylib (.so).
//
// On desktop, `main.rs` calls `app::app_main()` directly.
// On Android, the JVM loads the .so and invokes the JNI symbols
// that `app_main!()` auto-generates in `app.rs`.
// ────────────────────────────────────────────────────────────────────

// The cdylib target's entry points are auto-generated by the
// `app_main!()` macro. The compiler's dead-code analysis cannot
// trace through the macro expansion, so it incorrectly reports
// all items as unused. These allows are correct and expected.
#![allow(dead_code, unused_imports)]

// mimalloc uses TLS with the IE (Initial Exec) access model which
// causes `dlopen` to fail on Android with:
//   "TLS symbol (null) ... using IE access model"
// Android already ships scudo, so we simply skip the custom allocator.
#[cfg(not(target_os = "android"))]
use mimalloc::MiMalloc;
#[cfg(not(target_os = "android"))]
#[global_allocator]
static GLOBAL: MiMalloc = MiMalloc;

mod app;
mod aero_hud;
mod media_engine;
mod net_bridge;
mod remote_cursor;

/// Global profile name parsed from `--profile <NAME>` CLI arg.
/// On Android this stays uninitialized and defaults to the
/// standard identity path (no multi-profile needed on mobile).
pub static PROFILE: std::sync::OnceLock<Option<String>> = std::sync::OnceLock::new();
