[package]
name = "onyx-net"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
onyx-core  = { workspace = true }
onyx-store = { workspace = true }

# Iroh networking stack
iroh        = { workspace = true }
iroh-gossip = { workspace = true }

# Async / streaming
tokio        = { workspace = true }
futures-lite = { workspace = true }

# Compression
zstd = { workspace = true }

# Observability
tracing   = { workspace = true }
thiserror = { workspace = true }
anyhow    = { workspace = true }
